apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-minio
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-minio
    spec:
      containers:
        - name: minio
          image: {{ .Values.images.minio }}
          ports:
            - containerPort: 9000
            - containerPort: 9001
          env:
            - name: MINIO_ROOT_USER
              value: {{ .Values.env.MINIO_ROOT_USER }}
            - name: MINIO_ROOT_PASSWORD
              value: {{ .Values.env.MINIO_ROOT_PASSWORD }}
            - name: MINIO_DEFAULT_BUCKETS
              value: "{{ .Values.env.MINIO_BUCKET }},{{ .Values.env.MINIO_DEFAULT_BUCKETS }}"
            - name: STORAGE_BUCKET
              value: {{ .Values.env.MINIO_BUCKET }}
          resources:
            requests:
              cpu: {{ .Values.resources.minio.requests.cpu }}
              memory: {{ .Values.resources.minio.requests.memory }}
            limits:
              cpu: {{ .Values.resources.minio.limits.cpu }}
              memory: {{ .Values.resources.minio.limits.memory }}
          volumeMounts:
            - name: minio-data
              mountPath: /data
            - name: minio-default-icon
              mountPath: /default_icon
            - name: minio-official-plugin-icon
              mountPath: /official_plugin_icon
          command:
            - /bin/sh
            - -c
            - |
              (
                until (/usr/bin/mc alias set localminio http://localhost:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD) do
                  echo "Waiting for MinIO to be ready..."
                  sleep 1
                done

                /usr/bin/mc mb --ignore-existing localminio/$STORAGE_BUCKET
                /usr/bin/mc cp --recursive /default_icon/ localminio/$STORAGE_BUCKET/default_icon/
                /usr/bin/mc cp --recursive /official_plugin_icon/ localminio/$STORAGE_BUCKET/official_plugin_icon/

                echo "MinIO initialization complete."
              ) &

              exec minio server /data --console-address ":9001"
          livenessProbe:
            exec:
              command: ["bash", "-c", "/usr/bin/mc alias set health_check http://localhost:9000 {{ .Values.env.MINIO_ROOT_USER }} {{ .Values.env.MINIO_ROOT_PASSWORD }} && /usr/bin/mc ready health_check"]
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            retries: 3
      volumes:
        - name: minio-data
          emptyDir: {}
        - name: minio-default-icon
          configMap:
            name: {{ .Release.Name }}-minio-default-icon
        - name: minio-official-plugin-icon
          configMap:
            name: {{ .Release.Name }}-minio-official-plugin-icon
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-minio
spec:
  selector:
    app: {{ .Release.Name }}-minio
  ports:
    - port: 9000
      targetPort: 9000
    - port: 9001
      targetPort: 9001